"""Exported GP factor GP_ed2c09f43439ff39.

Generated by Genetic_Algorithm.export.export_factor. The literal ``_AST``
dictionary below is the complete formula; evaluation is delegated to
``Genetic_Algorithm.evaluator.evaluate_tree`` with the point-in-time
eligibility context injected by factor_common (``context_eligible``).
"""

from Genetic_Algorithm.evaluator import evaluate_tree
from Genetic_Algorithm.expression import (
    Node,
    expression_hash,
    validate_node_attributes,
)

TYPE = "regular"

META = {"factor_name": "GP_ed2c09f43439ff39", "author": "genetic_algorithm",
        "level": "daily", "category": "gp",
        "description": 'GP export GP_ed2c09f43439ff39 (expression ed2c09f43439ff3954db0897c3a09b2e978608fe24d2452bbe2c019a6a05c64a)'}

_EXPRESSION_HASH = "ed2c09f43439ff3954db0897c3a09b2e978608fe24d2452bbe2c019a6a05c64a"

_AST = {'op': 'negate', 'field': None, 'window': None, 'children': [{'op': 'rolling_mean', 'field': None, 'window': 3, 'children': [{'op': 'add', 'field': None, 'window': None, 'children': [{'op': 'body_relative', 'field': None, 'window': None, 'children': []}, {'op': 'rolling_max', 'field': None, 'window': 20, 'children': [{'op': 'range_relative', 'field': None, 'window': None, 'children': []}]}]}]}]}

SETTING = {"data_needed": ['close', 'high', 'low', 'open'], "universe": "historical_top50",
           "warmup_bars": 21, "preprocessing": "none",
           "params": {}, "factor_direction": 1,
           "context_eligible": True}


def _build_node(payload):
    node = Node(
        payload["op"],
        tuple(_build_node(child) for child in payload["children"]),
        field=payload["field"],
        window=payload["window"],
    )
    validate_node_attributes(node)
    return node


def calc_factor(data_ctx):
    tree = _build_node(_AST)
    if expression_hash(tree) != _EXPRESSION_HASH:
        raise ValueError(
            "exported AST does not match the recorded expression hash"
        )
    return evaluate_tree(tree, data_ctx, data_ctx["__eligible__"])
