"""Exported GP factor GP_c9bc24bbcfb2f0da.

Generated by Genetic_Algorithm.export.export_factor. The literal ``_AST``
dictionary below is the complete formula; evaluation is delegated to
``Genetic_Algorithm.evaluator.evaluate_tree`` with the point-in-time
eligibility context injected by factor_common (``context_eligible``).
"""

from Genetic_Algorithm.evaluator import evaluate_tree
from Genetic_Algorithm.expression import (
    Node,
    expression_hash,
    validate_node_attributes,
)

TYPE = "regular"

META = {"factor_name": "GP_c9bc24bbcfb2f0da", "author": "genetic_algorithm",
        "level": "daily", "category": "gp",
        "description": 'GP export GP_c9bc24bbcfb2f0da (expression c9bc24bbcfb2f0da4fe9bd7b9a4cce60c6b74e6e06ed2b584e389bd830d220c9)'}

_EXPRESSION_HASH = "c9bc24bbcfb2f0da4fe9bd7b9a4cce60c6b74e6e06ed2b584e389bd830d220c9"

_AST = {'op': 'multiply', 'field': None, 'window': None, 'children': [{'op': 'rolling_min', 'field': None, 'window': 40, 'children': [{'op': 'range_relative', 'field': None, 'window': None, 'children': []}]}, {'op': 'rolling_std', 'field': None, 'window': 40, 'children': [{'op': 'range_relative', 'field': None, 'window': None, 'children': []}]}]}

SETTING = {"data_needed": ['close', 'high', 'low'], "universe": "historical_top50",
           "warmup_bars": 39, "preprocessing": "none",
           "params": {}, "factor_direction": -1,
           "context_eligible": True}


def _build_node(payload):
    node = Node(
        payload["op"],
        tuple(_build_node(child) for child in payload["children"]),
        field=payload["field"],
        window=payload["window"],
    )
    validate_node_attributes(node)
    return node


def calc_factor(data_ctx):
    tree = _build_node(_AST)
    if expression_hash(tree) != _EXPRESSION_HASH:
        raise ValueError(
            "exported AST does not match the recorded expression hash"
        )
    return evaluate_tree(tree, data_ctx, data_ctx["__eligible__"])
